### ISSUE TITLE
Compiler scripts in `scripts` directory on builds

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/joern#115]
We want to ensure that scripts continue to work on changes in joern/codepropertygraph. Let's begin by compiling scripts on build, then creating tests for scripts and running them automatically.

**Comment by max-leuthaeuser** [comment]
Scripts in `joern/scripts/` are currently tested by running them with `io.shiftleft.console.query.DefaultCpgQueryExecutor`. There, [Scripted#eval](https://www.scala-lang.org/api/2.12.8/scala-compiler/scala/tools/nsc/interpreter/Scripted.html) is used that always compiles the provided code.
So from my point of view, this issue is resolved.
